# Generated by Django 4.2.4 on 2023-09-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
    ]
