# Generated by Django 4.2.4 on 2023-09-12 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='date_billing',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
