# Generated by Django 4.2.4 on 2023-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_billingaddress_date_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='region',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
